export const NAV_LINKS = [
  { label: 'Home', href: '/' },
  { label: 'How It Works', href: '/how-it-works' },
  { label: 'About', href: '/about' },
  { label: 'Reviews', href: '/reviews' },
  { label: 'Contact', href: '/contact' },
]

export const SERVICES = [
  {
    title: 'Resume Optimization',
    description: 'We rewrite, redesign, and ATS-optimize your resume so it actually gets past the filters and into human hands.',
    icon: 'FileText',
  },
  {
    title: 'LinkedIn Strategy',
    description: 'Full profile overhaul, targeted connection campaigns, and content suggestions that make recruiters come to you.',
    icon: 'Linkedin',
  },
  {
    title: 'Targeted Applications',
    description: 'We apply to roles that actually match your skills and goals. No spray-and-pray. Every application is intentional.',
    icon: 'Target',
  },
  {
    title: 'Recruiter Outreach',
    description: 'Direct messages to hiring managers and recruiters at your target companies, written to get responses.',
    icon: 'Send',
  },
  {
    title: 'Interview Prep Support',
    description: 'Mock interviews, curated question banks, and company research briefs so you walk in ready.',
    icon: 'MessageSquare',
  },
  {
    title: 'Weekly Progress Reports',
    description: 'Every week you see exactly what we did, how many applications went out, and what came back. Full transparency.',
    icon: 'BarChart3',
  },
]

export const TESTIMONIALS = [
  {
    text: 'Four months of applying on my own got me two phone screens. Two. Zytheq got me five interviews in the first three weeks. I am not even exaggerating.',
    role: 'Software Engineer',
    location: 'Austin',
    type: 'seeker' as const,
  },
  {
    text: 'I was mass-applying to 50 jobs a day and hearing nothing back. Turns out my resume was getting filtered out by ATS systems. Zytheq rebuilt it from scratch and the callbacks started within a week.',
    role: 'Data Analyst',
    location: 'Seattle',
    type: 'seeker' as const,
  },
  {
    text: 'The training sessions surprised me. I expected it to feel like a chore. Instead I found myself genuinely enjoying teaching someone how to navigate Excel like a pro.',
    role: 'Financial Analyst',
    location: 'New York',
    type: 'seeker' as const,
  },
  {
    text: 'My mentor taught me how to actually read a job description and tailor a response. That one skill changed how I approach everything.',
    role: 'MBA Student',
    location: 'Pune',
    type: 'student' as const,
  },
  {
    text: 'I was skeptical at first. No payment? What is the catch? Turns out there is no catch. They do your job search, you help a student. That is literally it.',
    role: 'Product Manager',
    location: 'Denver',
    type: 'seeker' as const,
  },
  {
    text: 'Zytheq handled my LinkedIn so well that recruiters started reaching out to ME. I went from chasing to being chased.',
    role: 'UX Designer',
    location: 'Portland',
    type: 'seeker' as const,
  },
  {
    text: 'I thought I knew how to make a presentation. Then my mentor showed me how people actually present in US companies. Completely different level.',
    role: 'Engineering Student',
    location: 'Hyderabad',
    type: 'student' as const,
  },
  {
    text: 'The weekly reports are what sold me. Every week I could see exactly what they did, how many applications, which companies, what responses came back. Full transparency.',
    role: 'Operations Manager',
    location: 'Atlanta',
    type: 'seeker' as const,
  },
  {
    text: 'I landed a role at a company I did not even know existed. Zytheq found it, applied, and prepped me for the interview. All I had to do was show up and be myself.',
    role: 'Marketing Specialist',
    location: 'Miami',
    type: 'seeker' as const,
  },
  {
    text: 'Honestly the evening sessions with my student became the thing I looked forward to most. Watching someone go from nervous to confident in a few weeks is something else.',
    role: 'Senior Developer',
    location: 'San Francisco',
    type: 'seeker' as const,
  },
  {
    text: 'My mentor did not just teach me tools. She taught me how to think about problems the way her team does. That is something no course can give you.',
    role: 'BCA Student',
    location: 'Chennai',
    type: 'student' as const,
  },
  {
    text: 'I had three offers within six weeks. Picked the one with the best culture fit. Zytheq even helped me negotiate the salary.',
    role: 'Business Analyst',
    location: 'Dallas',
    type: 'seeker' as const,
  },
  {
    text: 'The candidates I have sourced through Zytheq consistently outperform. Their resumes are clean, their LinkedIn profiles are sharp, and they interview well.',
    role: 'Technical Recruiter',
    location: 'San Jose',
    type: 'recruiter' as const,
  },
  {
    text: 'I was laid off and panicking. Zytheq took over my entire search so I could focus on not losing my mind. That alone was worth it.',
    role: 'Project Manager',
    location: 'Boston',
    type: 'seeker' as const,
  },
  {
    text: 'Before Zytheq I had never used Slack or Notion or any of these tools. Now I am comfortable with all of them. My mentor made it feel easy.',
    role: 'Commerce Student',
    location: 'Delhi',
    type: 'student' as const,
  },
  {
    text: 'What I appreciate most is that they do not just blast your resume everywhere. They actually read job descriptions and match you properly. Quality over quantity.',
    role: 'DevOps Engineer',
    location: 'Phoenix',
    type: 'seeker' as const,
  },
  {
    text: 'I went from mass-applying on my phone at 2 AM to actually sleeping well because I knew someone competent was handling it.',
    role: 'Graphic Designer',
    location: 'LA',
    type: 'seeker' as const,
  },
]

export const FAQ_DATA = [
  {
    question: 'Is this really free?',
    answer: 'Yes. No payment, no hidden fees, no "premium tier" reveal later. You contribute by spending a few hours training a student. That is the exchange. Your time for our expertise.',
  },
  {
    question: 'What kind of jobs do you help with?',
    answer: 'All industries, all levels. Tech, finance, healthcare, marketing, operations, creative, you name it. If you are looking for a job in the US market, we can help. Our team tailors the approach to your specific field and experience level.',
  },
  {
    question: 'How much time do the training sessions take?',
    answer: '1 to 3 hours per session, during US evening hours (9 to 11 PM your local time). Scheduling is flexible and worked out between you and your student. Most candidates find it fits naturally into their evening routine.',
  },
  {
    question: 'What do I teach the student?',
    answer: 'Real-world skills you already know. Building presentations, navigating workplace tools, handling assessments, professional communication, problem-solving approaches. We provide a framework and session guides so you are never guessing what to cover.',
  },
  {
    question: 'What if I have never taught anyone before?',
    answer: 'Perfect. You do not need to be a teacher. You need to be someone who works in the real world and can share what you know. Think of it less as teaching and more as showing someone the ropes. We provide structure and support throughout.',
  },
  {
    question: 'How long until I start getting interviews?',
    answer: 'Most candidates see callbacks within 2 to 4 weeks. It depends on your field, experience, and current market conditions. Some fields move faster than others, but we set realistic expectations from day one.',
  },
  {
    question: 'Do you apply to jobs without my approval?',
    answer: 'No. You set the parameters: target roles, companies, locations, salary range. We work within those boundaries. Nothing goes out without aligning with your preferences. You stay in control.',
  },
  {
    question: 'How do I know this is legitimate?',
    answer: 'Read our reviews from real candidates and students. Talk to our team on a free consultation call. Ask questions. We are real people solving a real problem, and we are happy to prove it before you commit.',
  },
]

export const STATS = [
  { value: 500, suffix: '+', label: 'Candidates Placed' },
  { value: 1200, suffix: '+', label: 'Student Sessions Completed' },
  { value: 150, suffix: '+', label: 'Partner Companies' },
  { value: 92, suffix: '%', label: 'Interview Conversion Rate' },
]

export const REVIEWS = [
  {
    id: 1,
    text: 'Four months of applying on my own got me two phone screens. Two. Zytheq got me five interviews in the first three weeks. I am not even exaggerating.',
    role: 'Software Engineer',
    location: 'Austin',
    type: 'seeker' as const,
    rating: 5,
    date: '2026-03-28',
    verified: true,
    response: null,
  },
  {
    id: 2,
    text: 'I was mass-applying to 50 jobs a day and hearing nothing back. Turns out my resume was getting filtered out by ATS systems. Zytheq rebuilt it from scratch and the callbacks started within a week.',
    role: 'Data Analyst',
    location: 'Seattle',
    type: 'seeker' as const,
    rating: 5,
    date: '2026-03-15',
    verified: true,
    response: 'Thank you for sharing this. ATS optimization is one of the first things we tackle, and we are glad it made a difference for you.',
  },
  {
    id: 3,
    text: 'The training sessions surprised me. I expected it to feel like a chore. Instead I found myself genuinely enjoying teaching someone how to navigate Excel like a pro.',
    role: 'Financial Analyst',
    location: 'New York',
    type: 'seeker' as const,
    rating: 5,
    date: '2026-02-20',
    verified: true,
    response: null,
  },
  {
    id: 4,
    text: 'My mentor taught me how to actually read a job description and tailor a response. That one skill changed how I approach everything.',
    role: 'MBA Student',
    location: 'Pune',
    type: 'student' as const,
    rating: 5,
    date: '2026-02-10',
    verified: true,
    response: null,
  },
  {
    id: 5,
    text: 'Solid experience. Got placed in 4 weeks. Would recommend.',
    role: 'Backend Developer',
    location: 'Chicago',
    type: 'seeker' as const,
    rating: 5,
    date: '2026-01-28',
    verified: true,
    response: null,
  },
  {
    id: 6,
    text: 'Zytheq handled my LinkedIn so well that recruiters started reaching out to ME. I went from chasing to being chased.',
    role: 'UX Designer',
    location: 'Portland',
    type: 'seeker' as const,
    rating: 5,
    date: '2026-01-15',
    verified: true,
    response: null,
  },
  {
    id: 7,
    text: 'I thought I knew how to make a presentation. Then my mentor showed me how people actually present in US companies. Completely different level.',
    role: 'Engineering Student',
    location: 'Hyderabad',
    type: 'student' as const,
    rating: 5,
    date: '2025-12-30',
    verified: true,
    response: null,
  },
  {
    id: 8,
    text: 'The process took longer than I expected, about six weeks before interviews started. But the team was communicative throughout and I ended up with two solid offers. Would have liked faster turnaround.',
    role: 'Marketing Coordinator',
    location: 'Minneapolis',
    type: 'seeker' as const,
    rating: 3,
    date: '2025-12-18',
    verified: true,
    response: 'We appreciate the honest feedback. Timelines can vary by field, but we are always working to improve our speed without sacrificing quality.',
  },
  {
    id: 9,
    text: 'I landed a role at a company I did not even know existed. Zytheq found it, applied, and prepped me for the interview. All I had to do was show up and be myself.',
    role: 'Marketing Specialist',
    location: 'Miami',
    type: 'seeker' as const,
    rating: 5,
    date: '2025-12-05',
    verified: true,
    response: null,
  },
  {
    id: 10,
    text: 'Honestly the evening sessions with my student became the thing I looked forward to most. Watching someone go from nervous to confident in a few weeks is something else.',
    role: 'Senior Developer',
    location: 'San Francisco',
    type: 'seeker' as const,
    rating: 5,
    date: '2025-11-22',
    verified: true,
    response: null,
  },
  {
    id: 11,
    text: 'My mentor did not just teach me tools. She taught me how to think about problems the way her team does. That is something no course can give you.',
    role: 'BCA Student',
    location: 'Chennai',
    type: 'student' as const,
    rating: 5,
    date: '2025-11-10',
    verified: true,
    response: null,
  },
  {
    id: 12,
    text: 'I had three offers within six weeks. Picked the one with the best culture fit. Zytheq even helped me negotiate the salary.',
    role: 'Business Analyst',
    location: 'Dallas',
    type: 'seeker' as const,
    rating: 5,
    date: '2025-10-28',
    verified: true,
    response: 'Congratulations on the offer. Salary negotiation is an underused tool, and we are glad we could help you get what you deserve.',
  },
  {
    id: 13,
    text: 'The candidates I have sourced through Zytheq consistently outperform. Their resumes are clean, their LinkedIn profiles are sharp, and they interview well.',
    role: 'Technical Recruiter',
    location: 'San Jose',
    type: 'recruiter' as const,
    rating: 5,
    date: '2025-10-15',
    verified: true,
    response: null,
  },
  {
    id: 14,
    text: 'I was laid off and panicking. Zytheq took over my entire search so I could focus on not losing my mind. That alone was worth it.',
    role: 'Project Manager',
    location: 'Boston',
    type: 'seeker' as const,
    rating: 4,
    date: '2025-10-02',
    verified: true,
    response: null,
  },
  {
    id: 15,
    text: 'Before Zytheq I had never used Slack or Notion or any of these tools. Now I am comfortable with all of them. My mentor made it feel easy.',
    role: 'Commerce Student',
    location: 'Delhi',
    type: 'student' as const,
    rating: 5,
    date: '2025-09-20',
    verified: true,
    response: null,
  },
  {
    id: 16,
    text: 'What I appreciate most is that they do not just blast your resume everywhere. They actually read job descriptions and match you properly. Quality over quantity.',
    role: 'DevOps Engineer',
    location: 'Phoenix',
    type: 'seeker' as const,
    rating: 5,
    date: '2025-09-08',
    verified: true,
    response: null,
  },
  {
    id: 17,
    text: 'I went from mass-applying on my phone at 2 AM to actually sleeping well because I knew someone competent was handling it.',
    role: 'Graphic Designer',
    location: 'LA',
    type: 'seeker' as const,
    rating: 4,
    date: '2025-08-25',
    verified: true,
    response: null,
  },
  {
    id: 18,
    text: 'I wish the student matching was a bit faster. It took about two weeks before my first session. But once it happened, the sessions were great and my student was eager to learn.',
    role: 'Systems Analyst',
    location: 'Detroit',
    type: 'seeker' as const,
    rating: 3,
    date: '2025-08-12',
    verified: true,
    response: 'We hear you on the matching timeline. We are actively working on reducing the wait by bringing in more students to the platform.',
  },
  {
    id: 19,
    text: 'The resume they built for me was night and day compared to what I had before. Professional, clean, and apparently ATS-friendly because the responses started coming.',
    role: 'Supply Chain Manager',
    location: 'Houston',
    type: 'seeker' as const,
    rating: 5,
    date: '2025-07-30',
    verified: true,
    response: null,
  },
  {
    id: 20,
    text: 'As a recruiter, I value pipelines that produce quality over volume. Zytheq does exactly that. Every candidate I have reviewed from them was well-prepared.',
    role: 'HR Manager',
    location: 'Charlotte',
    type: 'recruiter' as const,
    rating: 5,
    date: '2025-07-18',
    verified: true,
    response: null,
  },
  {
    id: 21,
    text: 'I learned more in six weeks of mentoring sessions than in an entire semester. My mentor explained things practically, not theoretically.',
    role: 'IT Student',
    location: 'Bangalore',
    type: 'student' as const,
    rating: 5,
    date: '2025-07-05',
    verified: true,
    response: null,
  },
  {
    id: 22,
    text: 'Was not sure about the training part at first, but my student asked such good questions that it actually sharpened my own thinking. Win-win is real here.',
    role: 'Product Designer',
    location: 'Nashville',
    type: 'seeker' as const,
    rating: 4,
    date: '2025-06-22',
    verified: true,
    response: null,
  },
  {
    id: 23,
    text: 'They did not just find me a job. They found me the right job. The one where I actually want to show up on Monday mornings.',
    role: 'Content Strategist',
    location: 'DC',
    type: 'seeker' as const,
    rating: 5,
    date: '2025-06-10',
    verified: true,
    response: null,
  },
  {
    id: 24,
    text: 'Good service overall. The applications were well-targeted. The only thing I would improve is more frequent check-ins during the first week.',
    role: 'QA Engineer',
    location: 'Tampa',
    type: 'seeker' as const,
    rating: 4,
    date: '2025-05-28',
    verified: true,
    response: 'Thanks for the feedback. We have since introduced a welcome call in the first 48 hours to set expectations clearly.',
  },
  {
    id: 25,
    text: 'My mentor walked me through how to use Jira, how standups work, and what people actually mean when they say "circle back." Genuinely useful.',
    role: 'CS Student',
    location: 'Mumbai',
    type: 'student' as const,
    rating: 5,
    date: '2025-05-15',
    verified: true,
    response: null,
  },
  {
    id: 26,
    text: 'I was skeptical. No cost? Sounded too good. But the model makes sense when you think about it, and the execution was solid. Got placed at a fintech company in five weeks.',
    role: 'Data Engineer',
    location: 'Denver',
    type: 'seeker' as const,
    rating: 5,
    date: '2025-05-02',
    verified: true,
    response: null,
  },
]

export const TEAM_MEMBERS = [
  {
    name: 'Founder & CEO',
    title: 'Building the bridge between opportunity and talent.',
    initials: 'ZF',
  },
  {
    name: 'Head of Candidate Success',
    title: 'Making sure every job seeker gets the attention they deserve.',
    initials: 'CS',
  },
  {
    name: 'Head of Student Programs',
    title: 'Curating mentorship experiences that actually matter.',
    initials: 'SP',
  },
  {
    name: 'Lead Resume Strategist',
    title: 'Turning careers into compelling stories on paper.',
    initials: 'RS',
  },
  {
    name: 'Head of Recruiter Partnerships',
    title: 'Connecting top talent with the companies that need them.',
    initials: 'RP',
  },
  {
    name: 'Operations Lead',
    title: 'Keeping everything running so nothing falls through the cracks.',
    initials: 'OL',
  },
]

export const VALUES = [
  {
    title: 'Transparency',
    description: 'You see everything we do. Weekly reports, open communication, no black boxes. If we are working for you, you should know exactly how.',
    icon: 'Eye',
  },
  {
    title: 'Mutual Growth',
    description: 'Every interaction on this platform makes two people better. The job seeker gets placed. The student gets real-world skills. That is the whole point.',
    icon: 'TrendingUp',
  },
  {
    title: 'Real-World Impact',
    description: 'We are not interested in theoretical value. We measure success in interviews landed, offers received, and students who walk into their first job feeling prepared.',
    icon: 'Zap',
  },
  {
    title: 'No Gatekeeping',
    description: 'Knowledge should not be locked behind paywalls or privilege. If you know something useful, share it. If you need help, ask for it. Simple.',
    icon: 'Unlock',
  },
]
